Ui/ViewComponents/NavbarViewComponent.cs
using Backend.Application.ViewModel;
using Backend.Domain.EntityClass;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ui.ViewComponents
{
    public class NavbarViewComponent:ViewComponent
    {
        private UserManager<User> _User;
        public NavbarViewComponent(UserManager<User> User)
        {
            _User = User;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _User.FindByNameAsync(User.Identity.Name);
            NavbarViewModel Model = new NavbarViewModel()
            {
                User = user,
                Role = await _User.GetRolesAsync(user)
            };
            return View(Model);
        }
    }
}

Ui/Views/Shared/_LayoutRoot.cshtml
@using Newtonsoft.Json
@using static Ui.Controllers.BaseController
<!DOCTYPE html>
<html class="loading light-layout dark-layout" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Dashboard analytics - Vuexy - Bootstrap HTML admin template</title>
    <link rel="apple-touch-icon" href="~/Admin/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/Admin/app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/vendors/css/charts/apexcharts.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/vendors/css/extensions/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/vendors/css/tables/datatable/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/vendors/css/tables/datatable/responsive.bootstrap.min.css">
    <!-- END: Vendor CSS-->
    <!--File Uplaoder css file-->
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/plugins/forms/form-file-uploader.css">
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/colors.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/components.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/themes/dark-layout.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/themes/bordered-layout.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/themes/semi-dark-layout.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/vendors/css/extensions/sweetalert2.min.css">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/plugins/charts/chart-apex.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/plugins/extensions/ext-component-toastr.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/pages/app-invoice-list.css">
    <!-- END: Page CSS-->
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/Admin/assets/css/style.css">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" type="text/css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Admin/app-assets/css/plugins/forms/form-quill-editor.css">
    <!-- END: Custom CSS-->
</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern  navbar-floating footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="">
    @await Component.InvokeAsync("Navbar")
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        @RenderBody()
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light"></footer>
    <button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>
    <!-- END: Footer-->


    <!-- BEGIN: Vendor JS-->
    <script src="~/Admin/app-assets/vendors/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="~/Admin/app-assets/vendors/js/charts/apexcharts.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/extensions/toastr.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/extensions/moment.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js"></script>
    <script src="~/Admin/app-assets/vendors/js/tables/datatable/responsive.bootstrap.min.js"></script>
    <!-- END: Page Vendor JS-->
    <!-- File upload developing file-->
    <script src="~/Admin/app-assets/js/scripts/forms/form-file-uploader.js"></script>
    <script src="~/Admin/app-assets/vendors/js/extensions/dropzone.min.js"></script>
    <!-- BEGIN: Theme JS-->
    <script src="~/Admin/app-assets/js/core/app-menu.js"></script>
    <script src="~/Admin/app-assets/js/core/app.js"></script>
    <!-- END: Theme JS-->
    <!--form repater-->
    <script src="~/Admin/app-assets/js/scripts/forms/form-repeater.js"></script>
    <script src="~/Admin/app-assets/vendors/js/forms/repeater/jquery.repeater.min.js"></script>
    <!--form repater finish-->
    <!-- BEGIN: Page JS-->
    <script src="~/Admin/app-assets/js/scripts/pages/dashboard-analytics.js"></script>
    <script src="~/Admin/app-assets/js/scripts/pages/app-invoice-list.js"></script>
    <script src="~/Admin/app-assets/vendors/js/extensions/sweetalert2.all.min.js"></script>
    <script src="~/Admin/app-assets/js/scripts/ui/ui-feather.js"></script>
    <!-- END: Page JS-->

    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })

    </script>
    <script src="~/Admin/app-assets/vendors/js/editors/quill/quill.min.js"></script>
    <script src="~/Admin/app-assets/js/scripts/forms/form-quill-editor.js"></script>
   @if(TempData["Message"] != null)
   {
        Message message = JsonConvert.DeserializeObject<Message>(TempData["Message"] as string);
        if (message.WindowType == WindowType.toastr)
        {
            <script>
                toastr['@message.Type'](
                    '@message.Body',
                    '@message.Header'
                );
            </script>
        }
        else
        {
            <script>
                Swal.fire({
                icon: '@message.Type',
                title: '@message.Header',
                text: '@message.Body',
                })
            </script>
           
    }
    }
</body>
<!-- END: Body-->
</html>