Ui/Controllers/RootController.cs
using Backend.Application.Abstract;
using Backend.Application.ViewModel;
using Backend.Domain.EntityClass;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Ui.Controllers.BaseController;

namespace Ui.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RootController : BaseController
    {
        private UserManager<User> _User;
        private RoleManager<IdentityRole> _Role;
        private IFileUpload _FileUpload;
        private IGenericRepository<SiteSetting> _Setting;

        public RootController(
            UserManager<User> User,
            RoleManager<IdentityRole> role,
            IFileUpload FileUpload,
            IGenericRepository<SiteSetting> setting
            )
        {
            _User = User;
            _Role = role;
            _FileUpload = FileUpload;
            _Setting = setting;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> RoleList()
        {
            var model = new RoleViewModel()
            {
                Roles = _Role.Roles,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> RoleList(RoleViewModel Model)
        {
            var result = await _Role.CreateAsync(new IdentityRole(Model.AddRole));
            var model = new RoleViewModel()
            {
                Roles = _Role.Roles,
            };
            if (result.Succeeded)
            {
                return View(model);
            }
            var message = "";
            foreach (var item in result.Errors)
            {
                message += $"{item.Description}<br>";
            }
            MessageCreate("System", message, Type.error, WindowType.sweet);
            return View(model);

        }
        [HttpGet]
        public async Task<IActionResult> RoleDelete(string? id)
        {
            if (string.IsNullOrEmpty(id))
            {
                MessageCreate("Role Error", "Role Id Is Null", Type.error, WindowType.toastr);
                return RedirectToAction("RoleList");
            }
            if(await _Role.FindByIdAsync(id) ==  null)
            {
                MessageCreate("Role Error", "Role Is Null", Type.error, WindowType.toastr);
                return RedirectToAction("RoleList");
            }
            var role = await _Role.FindByIdAsync(id);
            var result =await _Role.DeleteAsync(role);
            if (result.Succeeded)
            {
                MessageCreate("Role Process", "Role Is Deleted", Type.success, WindowType.toastr);
                return RedirectToAction("RoleList");
            }
            var message = "";
            foreach (var item in result.Errors)
            {
                message += $"{item.Description}<br>";
            }
            MessageCreate("System", message, Type.error, WindowType.sweet);
            return RedirectToAction("RoleList");
        }
        [HttpGet]
        public async Task<IActionResult> RoleUpdate(string id)
        {
            if (await _Role.FindByIdAsync(id) == null)
            {
                MessageCreate("Role Error", "Role Is Null", Type.error, WindowType.toastr);
                return RedirectToAction("RoleList");
            }
            var role =await _Role.FindByIdAsync(id);
            var RoleUser = new List<User>();
            var NonRoleUser = new List<User>();
            var users = _User.Users;
            foreach (var item in users)
            {
                if(await _User.IsInRoleAsync(item, role.Name))
                {
                    RoleUser.Add(item);
                }
                else
                {
                    NonRoleUser.Add(item);
                }
            }
            var model = new RoleViewModel()
            {
                NonUsers = NonRoleUser,
                RoleUsers = RoleUser,
                RoleName = role.Name,
                RoleId = role.Id
            };
            return View(model);

        }
        [HttpPost]
        public async Task<IActionResult> RoleUpdate(RoleViewModel Model, string[] NonUserAdd, string[] RoleUserAdd)
        {
            if (string.IsNullOrEmpty(Model.RoleName) || await _Role.FindByIdAsync(Model.RoleId) == null)
            {
                MessageCreate("Role Error", "Role Is Not Null", Type.error, WindowType.toastr);
                return RedirectToAction("RoleList");
            }
            var role = await _Role.FindByIdAsync(Model.RoleId);
            role.Name = Model.RoleName;
            var result = await _Role.UpdateAsync(role);
            if (result.Succeeded)
            {
                foreach (var item in NonUserAdd)
                {
                    var user = await _User.FindByIdAsync(item);
                    await _User.RemoveFromRoleAsync(user, role.Name);

                }
                foreach (var item in RoleUserAdd)
                {
                    var user = await _User.FindByIdAsync(item);
                    await _User.AddToRoleAsync(user, role.Name);
                }
                MessageCreate("Role Process", "Role Is Updated", Type.success, WindowType.toastr);
                return RedirectToAction("RoleList");
            }

            MessageCreate("Role Error", "", Type.error, WindowType.toastr);
            return RedirectToAction("");
        }
        [HttpGet]
        public async Task<IActionResult> UserList()
        {
            var list = new List<UserViewModel>();
            foreach (var item in _User.Users)
            {
                var model = new UserViewModel
                {
                    User = item,
                    Roles = await _User.GetRolesAsync(item)
                };
                list.Add(model);
            }
            return View(list);
        }
       [HttpGet]
       public async Task<IActionResult> UserEdit(string id)
       {
            //if string is null redirect your account edit
            if(await _User.FindByNameAsync(User.Identity.Name) == null)
            {
                MessageCreate("User Error", "User Id Is Not Found", Type.error, WindowType.toastr);
                return RedirectToAction("Login", "Account");
            }
            var user = await _User.FindByNameAsync(User.Identity.Name);
            if (!string.IsNullOrEmpty(id))
            {
                if (await _User.FindByIdAsync(id) == null)
                {
                    MessageCreate("User Error", "User Is Not Found", Type.error, WindowType.toastr);
                    return RedirectToAction("UserList");
                }
                user = await _User.FindByIdAsync(id);
            }
            var model = new UserViewModel();
            model.User = user;
            model.Roles = await _User.GetRolesAsync(user);
            ViewBag.Roles = new SelectList(_Role.Roles, "Id", "Name");
            return View(model);
       }
        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel Model,IFormFile FileImg)
        {
            var message = "";
            if (await _User.FindByIdAsync(Model.User.Id) == null)
            {
                MessageCreate("User Error", "User Is Not Found", Type.error, WindowType.toastr);
                return Redirect($"/User/{Model.User.Id}");
            }
            //UserName Check
            
            var user = await _User.FindByIdAsync(Model.User.Id);
            var oldUser = new User
            {
                UserName = user.UserName,
            };
            
            var userName = await _User.FindByNameAsync(Model.User.UserName);
            if(user != userName && userName != null)
            {
                if(user.UserName == user.UserName)
                {
                    MessageCreate("User Error", "User Id Is Not Found", Type.error, WindowType.toastr);
                    return Redirect($"/User/{Model.User.Id}");
                }
            }
            user.UserName = Model.User.UserName;
            user.Email = Model.User.Email;
            user.Name = Model.User.Name;
            user.LastName = Model.User.LastName;
            user.Age = Model.User.Age;
            user.ImgUrl = Model.User.ImgUrl;
            if (FileImg != null)
            {
                var random = $"{DateTime.UtcNow.Ticks}{Path.GetExtension(FileImg.FileName)}";
                if (!await _FileUpload.Send(FileImg, random, "jpg"))
                {
                    MessageCreate("Picture Error", "Picture is must jpg file", Type.error, WindowType.toastr);
                    return Redirect($"/User/{Model.User.Id}");
                }
                user.ImgUrl = random;
            }
            if (!string.IsNullOrEmpty(Model.NewPassword))
            {
                var token = await _User.GeneratePasswordResetTokenAsync(user);
                var state = await _User.ResetPasswordAsync(user,token,Model.NewPassword);
                if (!state.Succeeded)
                {
                    message += "";
                    foreach (var item in state.Errors)
                    {
                        message += $"{item.Description}<br>";
                        
                    }
                    MessageCreate("System", message, Type.error, WindowType.sweet);

                    return Redirect($"/User/{Model.User.Id}");
                }
                MessageCreate("User Process", "User Is Updated", Type.success, WindowType.toastr);
                return Redirect($"/User/{Model.User.Id}");
            }
            var result = await _User.UpdateAsync(user);
            if (result.Succeeded)
            {
                if(oldUser.UserName != user.UserName)
                {

Ui/Views/Root/RoleList.cshtml
@model RoleViewModel
@{
    Layout = "_LayoutRoot";
}
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <!-- users list start -->
        <section class="app-user-list">
            <!-- users filter start -->
            <div class="card">
               <div class="row">
                  <button class="dt-button add-new btn btn-primary m-2" tabindex="0" aria-controls="DataTables_Table_0" type="button" data-toggle="modal" data-target="#modals-slide-in"><span>Role Add</span></button>
               </div>
            </div>
            <!-- users filter end -->
            <!-- list section start -->
            @if(Model.Roles.Count() == 0){

                <div class="alert alert-danger">No Role</div>

            }
            <div class="card">
                <div class="table-responsive pt-0">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th></th>
                                <th>Role Id</th>
                                <th>Role Name</th>
                                <th>Role User Count</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Roles)
                            {
                                <tr>
                                    <td></td>
                                    <td>@item.Id</td>
                                    <td>@item.Name</td>
                                    <td>10</td>
                                    <td><a asp-controller="root" class="btn btn-primary mr-1 data-submit" asp-action="RoleUpdate" asp-route-id="@item.Id">Role Update</a><a asp-controller="root" class="btn btn-outline-secondary" asp-action="RoleDelete" asp-route-id="@item.Id">Role Delete</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- Modal to add new user starts-->
                <div class="modal modal-slide-in new-user-modal fade" id="modals-slide-in">
                    <div class="modal-dialog">
                        <form class="add-new-user modal-content pt-0" asp-action="RoleList" method="post">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">×</button>
                            <div class="modal-header mb-1">
                                <h5 class="modal-title" id="exampleModalLabel">New Role</h5>
                            </div>
                            <div class="modal-body flex-grow-1">
                                <div class="form-group">
                                    <label class="form-label" for="basic-icon-default-fullname">Role Name</label>
                                    <input asp-for="AddRole" value="@Model.AddRole" class="form-control dt-full-name" id="basic-icon-default-fullname" placeholder="John Doe"aria-label="John Doe" aria-describedby="basic-icon-default-fullname2" />
                                </div>
                                <button type="submit" class="btn btn-primary mr-1 data-submit">Submit</button>
                                <button type="reset" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Modal to add new user Ends-->
            </div>
            <!-- list section end -->
        </section>
        <!-- users list ends -->

    </div>
</div>

Ui/Views/Root/RoleUpdate.cshtml
@model RoleViewModel
@{
    Layout = "_LayoutRoot";
}
<form asp-controller="root" asp-action="RoleUpdate" method="post" class="invoice-repeater">
 <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Role Update</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a asp-action="index">Home</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="#">Role Update</a>
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <section class="form-control-repeater">
                    <div class="row">
                        <!-- Invoice repeater -->
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Invoice</h4>
                                </div>
                                <div class="card-body">
                                  
                                        <div data-repeater-list="invoice">
                                            <div data-repeater-item>
                                                <div class="row">
                                                    <div class="col-md-4 col-12">
                                                        <div class="form-group">
                                                            <label for="itemname">Role Name</label>
                                                            <input asp-for="RoleId" value="@Model.RoleId" type="hidden" class="form-control" id="itemname" aria-describedby="itemname"  />
                                                            <input asp-for="RoleName" value="@Model.RoleName"  class="form-control" id="itemname" aria-describedby="itemname"  />
                                                        </div>
                                                <div class="row">
                                                    <div class="col-12">
                                                        <button class="btn btn-icon btn-primary" type="submit" data-repeater-create>
                                                            <i data-feather="plus" class="mr-25"></i>
                                                            <span>Update Role</span>
                                                        </button>
                                                    </div>
                                                </div>
                                                    </div>
                                                    <div class="col-md-8 col-12 mb-50">
                                                        <div class="form-group">
                                                    <div class="card-datatable table-responsive pt-0">
                                                        <h4>Role User</h4>
                                                        <table class="dt-multilingual table">
                                                            <thead class="thead-light">
                                                                <tr>
                                                                    <th></th>
                                                                    <th>User Img</th>
                                                                    <th>Name Subname</th>
                                                                    <th>E Mail</th>
                                                                    <th>Role User Count</th>
                                                                    <th>Actions</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                @foreach (var item in Model.RoleUsers)
                                                                {
                                                                    <tr>
                                                                        <td><input type="checkbox" value="@item.Id" name="NonUserAdd"></td>
                                                                        <td><img src="~/Files/@item.ImgUrl"></td>
                                                                        <td>@item.UserName</td>
                                                                        <td>@item.Email</td>
                                                                        <td>@item.Active</td>
                                                                        <td><a asp-controller="root" class="btn btn-primary mr-1 data-submit" asp-action="RoleUpdate" asp-route-id="@item.Id">User View</a></td>
                                                                    </tr>
                                                                }
                                                            </tbody>
                                                        </table>
                                                        <h4>Role Non User</h4>
                                                        <table class="dt-multilingual table">
                                                            <thead class="thead-light">
                                                                <tr>
                                                                    <th></th>
                                                                    <th>User Img</th>
                                                                    <th>Name Subname</th>
                                                                    <th>E Mail</th>
                                                                    <th>Role User Count</th>
                                                                    <th>Actions</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                @foreach (var item in Model.NonUsers)
                                                                {
                                                                    <tr>
                                                                        <td><input type="checkbox" value="@item.Id" name="RoleUserAdd"></td>
                                                                        <td><img src="~/Files/@item.ImgUrl"></td>
                                                                        <td>@item.UserName</td>
                                                                        <td>@item.Email</td>
                                                                        <td>@item.Active</td>
                                                                        <td><a asp-controller="root" class="btn btn-primary mr-1 data-submit" asp-action="RoleUpdate" asp-route-id="@item.Id">User View</a></td>
                                                                    </tr>
                                                                }
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <hr />
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                        <!-- /Invoice repeater -->
                    </div>
                </section>

            </div>
        </div>
</form>

Ui/Views/Root/SiteConfig.cshtml
@model SiteConfigViewModel
@{
    Layout = "_LayoutRoot";
}
<div class="alert alert-danger" asp-validation-summary="All"></div>
<div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Form Validation</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a asp-action="index">Home</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="#">Settings</a>
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Validation -->
                <section class="bs-validation">
                    <div class="row">
                        <!-- jQuery Validation -->
                        <div class="col-md-6 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Database Datas</h4>
                                </div>
                                <div class="card-body">
                                    <form id="jquery-val-form" asp-controller="Root" asp-action="SiteConfig" method="post">
                                        <div class="row">
                                            <div class="col-md-6 col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Author Name</label>
                                                    <input class="form-control" asp-for="SiteAdmin" value="@Model.SiteAdmin" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Site Descriptions</label>
                                                    <input class="form-control" asp-for="SiteDescriptions" value="@Model.SiteDescriptions" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Meta Tags</label>
                                                    <input class="form-control" asp-for="MetaTags" value="@Model.MetaTags" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Site Logo</label>
                                                    <input class="form-control" type="File" name="SiteLogo" />
                                                    <input class="form-control" type="hidden" asp-for="SiteLogoUrl" value="@Model.SiteLogoUrl" />
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Host</label>
                                                    <input class="form-control" asp-for="Host" value="@Model.Host" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Smtp Host</label>
                                                    <input class="form-control" asp-for="SmtpHost" value="@Model.SmtpHost" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Smtp Port</label>
                                                    <input class="form-control" asp-for="SmtpPort" value="@Model.SmtpPort" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Smtp User</label>
                                                    <input class="form-control" asp-for="SmtpUser" value="@Model.SmtpUser" />
                                                </div>
                                                <div class="form-group">
                                                    <label class="form-label" for="basic-default-name">Smtp Password</label>
                                                    <input class="form-control" type="password" asp-for="SmtpPassword" value="@Model.SmtpPassword" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary" name="submit" value="Submit">Submit</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- /jQuery Validation -->
                    </div>
                </section>
                <!-- /Validation -->

            </div>